#!/bin/python3

import json
import os
import random
import re
import subprocess

xdg_data_home = os.environ.get("XDG_DATA_HOME", os.path.join(os.environ["HOME"], ".local", "share"))
userscripts_dir = os.path.join(xdg_data_home, "qutebrowser", "userscripts")
def dir(name):
    return os.path.join(userscripts_dir, name)

password = random.getrandbits(64)
authToken = bytes("%s" % random.getrandbits(64), 'utf-8')

# Start firenvim script, send password, get port
firenvim = subprocess.Popen(["/home/me/.local/share/firenvim/firenvim"], bufsize = 0, stdout = subprocess.PIPE, stdin = subprocess.PIPE, stderr = subprocess.PIPE)
request = 'abcde{"newInstance":true,"password":"' + str(password) + '"}'
firenvim.stdin.write(bytes(request, 'utf-8'))
out = b"";
while not out.endswith(b"}"):
    out += firenvim.stdout.read(1)
# Skipping first 4 bytes, which represent the length of the json string
result = json.loads(out[4:])

# Get the javascript that will run in the frame, insert port and password
# frame.js is src/qutebrowser-frame.ts
with open(dir("frame.js"), "rb") as f:
    framejs = f.read().replace(
        b'Promise.resolve({ port: "QUTEBROWSER_PORT", password: "QUTEBROWSER_PASSWORD" });',
        bytes('Promise.resolve({ port: %s, password: "%s" });' % (result["port"], password), 'utf-8'),
    ).replace(b"QUTEBROWSER_AUTH_TOKEN", authToken)

# Get the HTML of the frame, inline the frame's JS
# index.html is src/index.html
with open(dir("index.html"), "rb") as f:
    html = f.read()
    script_tag = html.find(b'<script type="application/javascript" src="index.js">')
    script_tag_end = html[script_tag:].find(b'</script>')
    html = html[0:script_tag] + b'<script>\n' + framejs + b'\n</script>' + html[script_tag_end:]

# Translate HTML to its Uint8Array, insert it in the script that will be executed by qutebrowser
# content.js is src/qutebrowser.ts
with open(dir("content.js"), "rb") as f:
    uint8_array = bytes(''.join([str(c) + "," for c in html]), 'utf-8')
    contentjs = f.read().replace(b"QUTEBROWSER_AUTH_TOKEN", authToken).replace(
        b"/* QUTEBROWSER_PAGE */",
        b"(new Uint8Array([" + uint8_array + b"])).buffer"
    )

# Write script to file
with open(dir("index.js"), "wb") as f:
    f.write(contentjs)

# Execute file
with open(os.environ["QUTE_FIFO"], "w") as f:
    f.write("jseval --file %s\n" % dir("index.js"))
    f.write("mode-enter passthrough")

firenvim.wait()
