export enum MessageType {
  // Background script functions
  ACCEPT_COMMAND = 'ACCEPT_COMMAND',
  CLOSE_OWN_TAB = 'CLOSE_OWN_TAB',
  GET_ERROR = 'GET_ERROR',
  GET_NEOVIM_INSTANCE = 'GET_NEOVIM_INSTANCE',
  GET_NVIM_PLUGIN_VERSION = 'GET_NVIM_PLUGIN_VERSION',
  GET_OWN_FRAME_ID = 'GET_OWN_FRAME_ID',
  GET_TAB = 'GET_TAB',
  GET_TAB_VALUE = 'GET_TAB_VALUE',
  GET_TAB_VALUE_FOR = 'GET_TAB_VALUE_FOR',
  GET_WARNING = 'GET_WARNING',
  MESSAGE_FRAME = 'MESSAGE_FRAME',
  MESSAGE_PAGE = 'MESSAGE_PAGE',
  PUBLISH_FRAME_ID = 'PUBLISH_FRAME_ID',
  SET_TAB_VALUE = 'SET_TAB_VALUE',
  TOGGLE_DISABLED = 'TOGGLE_DISABLED',
  UPDATE_SETTINGS = 'UPDATE_SETTINGS',
  OPEN_TROUBLESHOOTING_GUIDE = 'OPEN_TROUBLESHOOTING_GUIDE',

  // Content script functions (from page.ts)
  GET_ACTIVE_INSTANCE_COUNT = 'GET_ACTIVE_INSTANCE_COUNT',
  REGISTER_NEW_FRAME_ID = 'REGISTER_NEW_FRAME_ID',
  SET_DISABLED = 'SET_DISABLED',
  SET_LAST_FOCUSED_CONTENT_SCRIPT = 'SET_LAST_FOCUSED_CONTENT_SCRIPT',
  FORCE_NVIMIFY = 'FORCE_NVIMIFY',
  SEND_KEY = 'SEND_KEY',

  // Frame functions (from page.ts)
  EVAL_IN_PAGE = 'EVAL_IN_PAGE',
  FOCUS_INPUT = 'FOCUS_INPUT',
  FOCUS_PAGE = 'FOCUS_PAGE',
  FOCUS_NEXT = 'FOCUS_NEXT',
  FOCUS_PREV = 'FOCUS_PREV',
  GET_EDITOR_INFO = 'GET_EDITOR_INFO',
  GET_ELEMENT_CONTENT = 'GET_ELEMENT_CONTENT',
  HIDE_EDITOR = 'HIDE_EDITOR',
  KILL_EDITOR = 'KILL_EDITOR',
  PRESS_KEYS = 'PRESS_KEYS',
  RESIZE_EDITOR = 'RESIZE_EDITOR',
  SET_ELEMENT_CONTENT = 'SET_ELEMENT_CONTENT',
  SET_ELEMENT_CURSOR = 'SET_ELEMENT_CURSOR',
}

export interface Message {
  type: MessageType;
  args?: any[];
}
