name: Vint

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - '*'

jobs:
  vint:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Run vint with reviewdog
      uses: reviewdog/action-vint@v1.17.0
