name: Vint

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - '*'

jobs:
  vint:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Setup dependencies
      run: pip install setuptools vim-vint
    - name: Run Vimscript Linter
      run: vint .
